import type { FormFieldConfig } from "@/core/components/common";
import { DEFAULT_PRICE_OPTIONS } from "../../utils/customer-utils";

export const CUSTOMER_FIELDS: FormFieldConfig[] = [
	{
		name: "registerDate",
		label: "Register Date",
		type: "date",
		required: true,
		defaultValue: new Date().toISOString().split("T")[0],
	},
	{
		name: "code",
		label: "Code",
		type: "text",
		required: true,
		placeholder: "Enter customer code: CUSxxxxxx",
		pattern: {
			value: /^CUS\d{6}$/,
			message: "Code must be in format CUSxxxxxx (e.g., CUS123456)",
		},
	},
	{
		name: "name",
		label: "Name",
		type: "text",
		required: true,
		placeholder: "Enter customer name",
	},
	{
		name: "referredById",
		label: "Referred By",
		type: "select",
		options: [],
		placeholder: "Select referrer",
	},
	{
		name: "employeeId",
		label: "Employee",
		type: "select",
		required: true,
		options: [],
		placeholder: "Select employee",
	},
	{
		name: "defaultPrice",
		label: "Default Price",
		type: "select",
		options: DEFAULT_PRICE_OPTIONS,
		defaultValue: "retail_price",
	},
	{
		name: "telephone",
		label: "Telephone",
		type: "text",
		placeholder: "Enter phone number",
	},
	{
		name: "email",
		label: "Email",
		type: "text",
		placeholder: "Enter email address",
	},
	{
		name: "warehouse",
		label: "Warehouse",
		type: "select",
		options: [],
	},
	{
		name: "status",
		label: "Status",
		type: "switch",
		defaultValue: true,
		helperText: "Active/Inactive customer status",
	},
	{
		name: "geography",
		label: "Geography",
		type: "text",
		placeholder: "Enter geography/region",
	},
	{
		name: "location",
		label: "Location",
		type: "text",
		placeholder: "Enter location details",
	},
	{
		name: "map",
		label: "Map URL",
		type: "text",
		placeholder: "Enter Google Maps link",
	},
	{
		name: "profileUrl",
		label: "Profile URL",
		type: "text",
		placeholder: "Enter profile image URL",
		helperText: "URL for customer profile image",
	},
	{
		name: "shopBannerUrl",
		label: "Shop Banner URL",
		type: "text",
		placeholder: "Enter shop banner image URL",
		helperText: "URL for shop banner image",
	},
	{
		name: "address",
		label: "Address",
		type: "textarea",
		placeholder: "Enter full address",
		className: "col-span-2",
	},
	{
		name: "billingAddress",
		label: "Billing Address",
		type: "textarea",
		placeholder: "Enter billing address",
		className: "col-span-2",
	},
	{
		name: "deliveryAddress",
		label: "Delivery Address",
		type: "textarea",
		placeholder: "Enter delivery address",
		className: "col-span-2",
	},
	{
		name: "memo",
		label: "Memo",
		type: "textarea",
		placeholder: "Enter additional notes",
		helperText: "Additional notes or comments about the customer",
		className: "col-span-2",
	},
];
